[package]
name = "raytracer"
version = "0.1.0"
authors = ["Dobiasd <editgym@gmail.com>"]
edition = "2018"

[dependencies]
pixel-canvas = "0.2.1"
rand = "0.7.3"

[[bin]]
name = "main"
path = "src/main.rs"
