# Very slow and very nice
#resolution_x = 1920
#resolution_y = 1080
#samples_per_pixel = 1024
#max_depth = 32
#display_scale_factor = 1
#speed = 2.3
#num_frames = 1000

# Fast and ugly
resolution_x = 192
resolution_y = 108
samples_per_pixel = 8
max_depth = 4
display_scale_factor = 5
speed = 2.3
num_frames = 240
